import type { Config } from 'tailwindcss';

export default {
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				'surface-container-lowest': '#ffffff',
				surface: '#fbf9f8',
				primary: '#000613',
				'primary-fixed': '#d4e3ff',
				'on-tertiary-fixed': '#351002',
				outline: '#74777f',
				'inverse-primary': '#afc8f0',
				'on-primary': '#ffffff',
				secondary: '#ba0b00',
				error: '#ba1a1a',
				'surface-container-low': '#f6f3f2',
				'inverse-surface': '#303030',
				tertiary: '#110200',
				'on-surface': '#1b1c1c',
				'tertiary-container': '#391303',
				'surface-dim': '#dcd9d9',
				'on-secondary-fixed': '#400100',
				'inverse-on-surface': '#f3f0f0',
				'surface-container': '#f0eded',
				'surface-container-high': '#eae8e7',
				'on-primary-container': '#6f88ad',
				'on-tertiary-fixed-variant': '#6b3a25',
				'secondary-fixed': '#ffdad4',
				'error-container': '#ffdad6',
				'secondary-fixed-dim': '#ffb4a7',
				'on-secondary': '#ffffff',
				'border-light': '#EBEBEB',
				'on-error': '#ffffff',
				'surface-variant': '#e4e2e1',
				'surface-container-highest': '#e4e2e1',
				'surface-bright': '#fbf9f8',
				'on-primary-fixed': '#001c3a',
				'primary-fixed-dim': '#afc8f0',
				'on-primary-fixed-variant': '#2f486a',
				'accent-orange': '#F97316',
				'on-tertiary': '#ffffff',
				'surface-muted': '#F8FAFC',
				'on-secondary-container': '#fffbff',
				'on-surface-variant': '#43474e',
				'on-error-container': '#93000a',
				'tertiary-fixed-dim': '#fdb69a',
				background: '#FFFFFF',
				'on-background': '#1b1c1c',
				'surface-tint': '#476083',
				'primary-container': '#001f3f',
				'outline-variant': '#c4c6cf',
				'on-secondary-fixed-variant': '#920700',
				'tertiary-fixed': '#ffdbce',
				'on-tertiary-container': '#b5785f',
				'secondary-container': '#e61c0a',
			},
			borderRadius: {
				DEFAULT: '0.25rem',
				lg: '0.5rem',
				xl: '0.75rem',
				full: '9999px',
			},
			spacing: {
				lg: '48px',
				base: '8px',
				md: '24px',
				xs: '4px',
				'container-max': '1280px',
				sm: '12px',
				xl: '80px',
				gutter: '20px',
			},
			fontFamily: {
				'label-sm': ['Manrope'],
				'display-lg': ['Manrope'],
				'headline-lg-mobile': ['Manrope'],
				'headline-lg': ['Manrope'],
				'headline-md': ['Manrope'],
				'body-md': ['Manrope'],
				'label-md': ['Manrope'],
				'body-lg': ['Manrope'],
			},
			fontSize: {
				'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
				'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
				'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
				'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
				'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
				'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
				'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
				'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
			},
		},
	},
};
